### ISSUE TITLE
A saída de brazilnum.cep.format_cep está diferente do padrão dos Correios

### ISSUE THREAD

**Issue by ptronico** [poliquin/brazilnum#7]
A função `brazilnum.cep.format_cep` está retornando um zero a mais do que o devido, pelo menos levando em consideração o documento "[Estrutura do CEP](http://www.correios.com.br/para-voce/precisa-de-ajuda/o-que-e-cep-e-por-que-usa-lo/estrutura-do-cep)" dos Correios. Veja abaixo:

`In [15]: format_cep('60165180')`
`Out[15]: '060165-180'`

A saída não deveria ser `60165-180`? Obrigado!

**Comment by poliquin** [comment]
Sim, este é um erro! Vou corrigir isso rapidamente.

**Comment by poliquin** [comment]
Isto deve ser corrigido na versão 0.8.6 (This should be fixed in version 0.8.6). Re-install as follows:

```
pip install --upgrade brazilnum
```

Eu estou trabalhando em melhores testes.
