### ISSUE TITLE
validate_cpf quebra com letras

### ISSUE THREAD

**Issue by iurisilvio** [poliquin/brazilnum#9]
``` python
>>> validate_cpf("abc")
ValueError: invalid literal for int() with base 10: ''
```

**Comment by poliquin** [comment]
Obrigado. O problema deve ser corrigido. A nova versão está disponível via `pip`. Executar `pip install --upgrade brazilnum`.

Este problema sublinha a necessidade de um melhor tratamento de vários tipos. Eu abri um novo problema, #10, para corrigir isso.
